### PR TITLE
REP-131 Change local area to be automatically determined from the address.

### PR DESCRIPTION
**Pull request by edwh**
Lots in this:

- Introduce the areas table, with a migration to set up the ones we use.
- Change the localArea column to be a foreign key into the areas table, and set it in the migration.
- Add/rename localAreaName, which is determined using a join.  I bypassed the Doctrine/Repository stuff for this because it was getting on my nerves - see what you think.  There's probably a Doctrine way of doing this using associations, but I think I'd have to introduce a new model for the areas and this story is already getting a bit chunky.
- Re-geocode when we save an address in case the location has changed (existing bug).
- Change the area to be a read-only field.

### CODE REVIEW

**Comment by edwh** [comment]
> local_area_name

Well, this is a pain.  

You need the field in doctrine-mappings.php for it to be returned when reading.  But then it tries to insert it when writing.  

I can find no straightforward way to prevent that happening.  I'll come back to it.

**Comment by edwh** [comment]
Having banged my head some more, I have something that works, though it is very ugly.

**Review by ngm — APPROVED** [review]
Functionality works for me now! :tada: 

I must say, Doctrine appears to be more trouble than it is worth here.  Unless we are doing something non-standard, although joining to another table doesn't seem that out of the ordinary.

**Comment by edwh** [comment]
I think Doctrine has a way of doing it, but it would require us to create a model for the area, and return that as an object rather than a field.  I suspect if I was used to Doctrine I would have just done that to start off with.

**Pull request merged**
