### PR TITLE
Laravel 7.x Shift

### PR DESCRIPTION
**Pull request by restart-tech**
This pull request includes the changes for upgrading to Laravel 7.x. Feel free to commit any additional changes to the `shift-79785` branch.

**Before merging**, you need to:

- Checkout the `shift-79785` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by restart-tech** [comment]
:information_source: Shift noticed you have additional namespaces in your application. You may use the [Consolidate Namespaces Shift](https://laravelshift.com/laravel-consolidate-custom-namespaces) to simplify your namespaces into the default Laravel `App` namespace.

**Comment by restart-tech** [comment]
:warning: Laravel 7 removed "factory types". While available, this was undocumented since [Laravel 5.2](https://laravel.com/docs/5.2/testing#model-factories). Since then the preferred method has been [factory states](https://laravel.com/docs/7.x/database-testing#factory-states).

Shift converted usages of `$factory->defineAs()` to `$factory->state()`. However, you should [review this commit](https://github.com/TheRestartProject/RepairDirectory/pull/190/commits/b849adc34ff865d80bebad2b5853fad33fa12022?w=1) and run your tests to see if any additional changes to your _factory states_ are necessary.

**Comment by restart-tech** [comment]
:warning: The `MAIL_DRIVER` environment variable was renamed in Laravel 7 to `MAIL_MAILER` in order to support multiple mail configurations.

Shift attempted to [automate this change](https://github.com/TheRestartProject/RepairDirectory/pull/190/commits/df9aea7a87a296cca57039875ccb367035450573?w=1), but you should review any additional environment configuration and update to the new variable name.

**Comment by restart-tech** [comment]
:warning: Shift upgraded your configuration files by defaulting them and merging your _true customizations_. These include values which are not changeable through core `ENV` variables.

You should [review this commit](https://github.com/TheRestartProject/RepairDirectory/pull/190/commits/4b1be1a375942f365c19727fb5fa768b16916faf?w=1) for additional customizations or opportunities to use new `ENV` variables. If you have a lot of customizations, you may undo this commit with `git revert 4b1be1a3` and make the [config file changes](https://github.com/laravel-shift/laravel-6.0/pull/7/commits/e3379a9dcc2b08adf5934a99148366838371bc68) manually.

**Comment by restart-tech** [comment]
:information_source: Shift [updated your dependencies](https://github.com/TheRestartProject/RepairDirectory/pull/190/commits/72f101bebd68c75a2256e08f9750c50495a28d8d?w=1) for Laravel 7. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 7. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any Composer issues.

**Comment by restart-tech** [comment]
:information_source: Laravel 7 removed some of the PHPUnit configuration in favor of the defaults. While this is not a required changed, it is a good opportunity to compare your `phpunit.xml`  with the [default Laravel 7 version](https://github.com/laravel-shift/laravel-7.x/blob/master/phpunit.xml) to modernize your configuration.

**Comment by restart-tech** [comment]
:warning: Shift found potential uses of the `different` validation rule. In Laravel 7, this rule will fail if one of the specified parameters is missing from the request. As this was likely the expected behavior, it should not affect your validation. Nonetheless you should be aware of this change.

**Comment by restart-tech** [comment]
:warning: Laravel 7 uses a new date format when serializing models. The previous format was `2019-12-02 20:01:00`. Now, dates are serialized using an ISO-8601 compatible date format of `2019-12-02T20:01:00.283041Z` in `UTC`.

**This does not affect how dates are stored**. Only how they are serialized when using the `toArray` or `toJson` Eloquent methods.

If you need to preserve the previous format, you may override the `serializeDate` method on your model. Review the [Date Serialization](https://laravel.com/docs/7.x/upgrade#date-serialization) section of the _Upgrade Guide_ for more details.

**Comment by restart-tech** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 5. If you are directly interacting with any Symfony component, you should review the [Symfony change log](https://github.com/symfony/symfony/blob/5.x/UPGRADE-5.0.md) for additional changes.

**Comment by restart-tech** [comment]
:warning: Laravel 7.x has reached [end of life](https://laravelversions.com/). It no longer receives bug fixes or security updates. Shift recommends continuing to upgrade to the latest version (Laravel 9.x).

For tips on running multiple Shifts effectively, watch [upgrading old Laravel applications](https://laravelshift.com/videos/upgrading-old-laravel-applications).

**Comment by edwh** [comment]
Superceded by 9.x shift.

**Pull request closed without merging**
