### PR TITLE
RESTART-60 Change the default view for the map to be all of london and showing pins

### PR DESCRIPTION
**Pull request by mattKendon**
### Description

When the map is first loaded it should be zoomed out and centered on london. It should also show all pins within something like a 15 mile radius. 

### Action

Changed how the initial search happens on a page so that without any search parameters it will load all pins in a 15 mile radius of the location `London, UK` and will zoom out the map to be able to show them all. The centre of the map on initial reload has also be changed.

### CODE REVIEW

**Comment by ngm** [comment]
Thanks @mattKendon:

- can the input labelled 'Where do you live?' be prepopulated with the search text, i.e. 'London, UK'
- the results for this search are only bringing back 96 results, but there are 100 published business (perhaps just need bigger radius for the default)

**Comment by mattKendon** [comment]
@ngm do you mean as the placeholder text, or as the actual value of the input field?

I'll try with a wider radius to get the missing 4 businesses

**Comment by ngm** [comment]
@mattKendon - the actual value.  It then gets included should they choose to share results.

**Comment by mattKendon** [comment]
I;ve given this a go.  The location field now says `London, UK` by default. I've also set the default radius value to `All of London` as otherwise the way that the determine whether this should be zoomed out doesn't work (previously it was if the value of `location` was empty).

**Pull request merged**
